### ISSUE TITLE
A possible edge case.

### ISSUE THREAD

**Issue by luwei0917** [PureseqTM/PureseqTM_Package#1]
I tried to predict one seq:
>CRYSTAL_STRUCTURE:A|PDBID|CHAIN|SEQUENCE
ESPKEHDPFTYDYQSLQIGGLVIAGILFILGILIVLSRRCRCKFNQQQRTGEPDEEEGTFRSSIRRLSTRRR

The .top file I got is.
>crystal_structure
ESPKEHDPFTYDYQSLQIGGLVIAGILFILGILIVLSRRCRCKFNQQQRTGEPDEEEGTFRSSIRRLSTRRR
000000000000000000000000000000000000000000000000000000000000000000000000

But The .prob file is:
   1 E 0 0.003 
   2 S 0 0.000 
   3 P 0 0.000 
   4 K 0 0.000 
   5 E 0 0.000 
   6 H 0 0.000 
   7 D 0 0.000 
   8 P 0 0.001 
   9 F 0 0.003 
  10 T 0 0.007 
  11 Y 0 0.015 
  12 D 0 0.029 
  13 Y 0 0.058 
  14 Q 0 0.103 
  15 S 0 0.154 
  16 L 0 0.245 
  17 Q 0 0.365 
  18 I 0 0.542 
  19 G 0 0.694 
  20 G 0 0.799 
  21 L 0 0.867 
  22 V 0 0.912 
  23 I 0 0.947 
  24 A 0 0.966 
  25 G 0 0.978 
  26 I 0 0.987 
  27 L 0 0.989 
  28 F 0 0.984 
  29 I 0 0.978 
  30 L 0 0.970 
  31 G 0 0.947 
  32 I 0 0.917 
  33 L 0 0.885 
  34 I 0 0.806 
  35 V 0 0.668 
  36 L 0 0.580 
  37 S 0 0.470 
  38 R 0 0.282 
  39 R 0 0.175 
  40 C 0 0.120 
  41 R 0 0.075 
  42 C 0 0.030 
  43 K 0 0.016 
  44 F 0 0.013 
  45 N 0 0.010 
  46 Q 0 0.006 
  47 Q 0 0.003 
  48 Q 0 0.002 
  49 R 0 0.001 
  50 T 0 0.001 
  51 G 0 0.001 
  52 E 0 0.001 
  53 P 0 0.002 
  54 D 0 0.002 
  55 E 0 0.002 
  56 E 0 0.002 
  57 E 0 0.003 
  58 G 0 0.003 
  59 T 0 0.004 
  60 F 0 0.005 
  61 R 0 0.004 
  62 S 0 0.001 
  63 S 0 0.001 
  64 I 0 0.003 
  65 R 0 0.003 
  66 R 0 0.001 
  67 L 0 0.003 
  68 S 0 0.003 
  69 T 0 0.001 
  70 R 0 0.000 
  71 R 0 0.001 
  72 R 0 0.005 

Those with prob higher than 0.5 is not assigned to 1.(res 18 to 36)
I tried to understand why, it seems due to .pbseg file is empty.

The problem magically disappeared when I change the fasta to:
>CRYSTAL_STRUCTURE
ESPKEHDPFTYDYQSLQIGGLVIAGILFILGILIVLSRRCRCKFNQQQRTGEPDEEEGTFRSSIRRLSTRRR

just removing ":A|PDBID|CHAIN|SEQUENCE" somehow solved it.

**Comment by realbigws** [comment]
Dear LuWei.

Thank you so much for pointing this issue.

As as you've found, I figured out that this bug resides in "phobius" to produce the ".pbseg" file. 

Since the code in "phobius" is not that easy to be fixed, I slightly changed the code in "PureseqTM.sh" to fix this bug.

Please try again and the result shall be as expected.

Best,
-Sheng
